### ISSUE TITLE
Cannot find module 'Q'

### ISSUE THREAD

**Issue by Angularjschile** [joelcoxokc/slush-y#1]
help 
to build the project I get this error

Cannot find module 'Q'

**Comment by joelcoxokc** [comment]
I am not getting this error. I am trying to fix it. I have npm installed --saved q.

If you can find the issue let me know.

**Comment by collinwu** [comment]
Hey Joel,

I'm getting the same error.

My commands:
- run: slush y
- run: npm init
- run: npm install
- run: gulp

Error msg:
node_modules/gulp-bower/node_modules/bower/node_modules/q/q.js:126
                    throw e;
                          ^
angular: Unable to find suitable version for angular

**Comment by collinwu** [comment]
I got gulp to run when I ran a `bower install q --save`

Then in terminal, it prompts you to select a suitable version of angular with the following prompt: 

> Unable to find a suitable version for angular, please choose one:
>    1) angular#~1.2.6 which resolved to 1.2.26 and is required by angular-socket-io#0.6.0
>    2) angular#1.3.2 which resolved to 1.3.2 and is required by angular-cookies#1.3.2, angular-mocks#1.3.2, angular-resource#1.3.2, angular-sanitize#1.3.2, angular-scenario#1.3.2, angular-touch#1.3.2
>    3) angular#\* which resolved to 1.3.2 and is required by memesnmoods, restangular#1.4.0
>    4) angular#>=1 which resolved to 1.3.2 and is required by angular-bootstrap#0.11.2
>    5) angular#>= 1.0.2 which resolved to 1.3.2 and is required by angular-ui-utils#0.1.1
>    6) angular#>= 1.0.8 which resolved to 1.3.2 and is required by angular-ui-router#0.2.11Prefix the choice with ! to persist it to bower.json

Would it solve the problem if bower specified `q#1.0.1` ?

Running bower install q gives me 2.0.2 in bower.json

**Comment by joelcoxokc** [comment]
@collinwu Are you still getting the module q error? I am unable to recreate the error on either of my machines. I am currently trying to resolve the angular version request from bower. 

The bower version request is not an error, but it is unable to decide what the best version of angular to download is.

If you module q issue is resolved, then let me know so I can close this issue.

**Comment by collinwu** [comment]
@joelcoxokc everything worked for me when I did a `bower install q --save`

Cheers

**Comment by joelcoxokc** [comment]
BTW I am back at Hack Reactor if you want some help.

**Comment by OscarBakker** [comment]
I am getting the same error:

 ~/code/my-slush-y/app  slush y

module.js:340
    throw err;
          ^
Error: Cannot find module 'Q'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/slush-y/slushy/_Slushy/config/index.js:6:17)
    at Object.<anonymous> (/usr/lib/node_modules/slush-y/slushy/_Slushy/config/index.js:71:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
